### ISSUE TITLE
crash on loading front page

### ISSUE THREAD

**Issue by dbpokorny** [botwillacceptanything/botwillacceptanything#439]
Getting this after a clean test install on Linux and Mac OS: clone, npm install, node main.js, crash

TypeError: Cannot use 'in' operator to search for 'data' in null
   at Object.compile (/Users/dbp/github/test/botwillacceptanything/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:467:19)
   at HandlebarsEnvironment.hb.compile (/Users/dbp/github/test/botwillacceptanything/node_modules/express-handlebars/node_modules/handlebars/dist/cjs/handlebars.js:34:41)
   at ExpressHandlebars._compileTemplate (/Users/dbp/github/test/botwillacceptanything/node_modules/express-handlebars/lib/express-handlebars.js:239:28)
   at ExpressHandlebars.<anonymous> (/Users/dbp/github/test/botwillacceptanything/node_modules/express-handlebars/lib/express-handlebars.js:124:25)
   at /Users/dbp/github/test/botwillacceptanything/node_modules/express-handlebars/node_modules/promise/lib/core.js:33:15
   at flush (/Users/dbp/github/test/botwillacceptanything/node_modules/express-handlebars/node_modules/promise/node_modules/asap/asap.js:27:13)
   at process._tickCallback (node.js:419:13)

**Comment by SpenserJ** [comment]
Resolved in #441
