### ISSUE TITLE
Huge delay in "Vote comment" and faulty update of website

### ISSUE THREAD

**Issue by OLef1air** [botwillacceptanything/botwillacceptanything#476]
I have only little experience with Node and couldn't find the source of the problems causing this error in the stdout: 
```
[ERROR] TypeError: Cannot read property 'repo' of undefined
    at EventEmitter.eventsCommentCreated (/home/bot/botwillacceptanything/lib/voting/voting.js:117:47)
    at EventEmitter.emit (events.js:107:17)
    at /home/bot/botwillacceptanything/lib/routes/webhook.js:54:24
    at Layer.handle [as handle_request] (/home/bot/botwillacceptanything/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/bot/botwillacceptanything/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/home/bot/botwillacceptanything/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/home/bot/botwillacceptanything/node_modules/express/lib/router/layer.js:82:5)
    at /home/bot/botwillacceptanything/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/home/bot/botwillacceptanything/node_modules/express/lib/router/index.js:321:12)
    at next (/home/bot/botwillacceptanything/node_modules/express/lib/router/index.js:261:10)
```

**Comment by dbpokorny** [comment]
What steps reproduce the problem?

**Comment by OLef1air** [comment]
I can't reproduce it, but it is happening in the production env on botwillacceptanything.com

**Comment by minhoryang** [comment]
same here!
