### ISSUE TITLE
can't run from dev box

### ISSUE THREAD

**Issue by uptownhr** [botwillacceptanything/botwillacceptanything#491]
Should we be able to run the bot from our dev box? Credentials not in the repo? 
```
npm run-script main                                                                                                                                           uptown@Jamess-MacBook-Pro-2

> botwillacceptanything@0.0.1 main /Users/uptown/Projects/botwillacceptanything
> node main.js

Kawoda Doqo the great Bot of Kittens
Initializing middleware.
Initializing integrations.
Initializing secrets.yml
Loading /Users/uptown/Projects/botwillacceptanything/lib/middleware/bodyParser.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/middleware/errorHandler.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/middleware/favicon.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/middleware/logger.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/middleware/publicViews.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/middleware/static.js
Initializing routes.
Loading /Users/uptown/Projects/botwillacceptanything/lib/integrations/github_labels.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/integrations/irc.js
No IRC settings in config. IRC bot disabled.
Loading /Users/uptown/Projects/botwillacceptanything/lib/integrations/twitter.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/routes/commits.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/routes/root.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/routes/secrets.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/routes/statistics.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/routes/stdout.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/routes/video.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/routes/votes.js
Loading /Users/uptown/Projects/botwillacceptanything/lib/routes/webhook.js
Starting webserver at port 3000
Bot is initialized. HEAD: 4d67d4a9dce69a49dbf855a3ff5025289314bd46
[ERROR] Error getting comments of talk thread. { [Error: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}]
  message: '{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}',
  code: 401 }
[ERROR] UNCAUGHT ERROR: TypeError: Cannot call method 'some' of undefined
TypeError: Cannot call method 'some' of undefined
    at containsLabel (/Users/uptown/Projects/botwillacceptanything/lib/integrations/github_labels.js:165:35)
    at /Users/uptown/Projects/botwillacceptanything/lib/integrations/github_labels.js:159:30
    at Array.filter (native)
    at findLabelsToCreate (/Users/uptown/Projects/botwillacceptanything/lib/integrations/github_labels.js:157:39)
    at ensureRepoHasLabels (/Users/uptown/Projects/botwillacceptanything/lib/integrations/github_labels.js:140:32)
    at /Users/uptown/Projects/botwillacceptanything/lib/integrations/github_labels.js:29:21
    at Object.proto.sendError (/Users/uptown/Projects/botwillacceptanything/node_modules/github/api/v3.0.0/index.js:32:13)
    at /Users/uptown/Projects/botwillacceptanything/node_modules/github/api/v3.0.0/issues.js:733:29
    at callCallback (/Users/uptown/Projects/botwillacceptanything/node_modules/github/index.js:743:17)
    at IncomingMessage.<anonymous> (/Users/uptown/Projects/botwillacceptanything/node_modules/github/index.js:793:25)
[ERROR] Error getting stargazers: { [Error: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}]
  message: '{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}',
  code: 401 }
[ERROR] Error getting Pull Requests. { [Error: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}]
  message: '{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}',
  code: 401 }
```

**Comment by SpenserJ** [comment]
You need to provide your own github credentials, and set the bot up to run from your fork. Otherwise we'd have chaos in the issues on the main repo.

**Comment by uptownhr** [comment]
ah got it. why would there be chaos in the main repo though?

**Comment by SpenserJ** [comment]
If everyone had the access tokens for the bot's account, the polling request limit would be used up, multiple bots may try to act on the same issue at once, and users could change the limits on voting or even merge/close PRs themselves.

**Comment by uptownhr** [comment]
maybe we should work on an API for forked bots to connect to
